name: "Build, Test, Scan"
on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
jobs:
  jar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven clean
        run: mvn clean --batch-mode
      - name: Set up codeql
        uses: github/codeql-action/init@v2
        with:
          languages: java
      - name: Build and test with Maven
        run: mvn --batch-mode -fn package
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: target/reports/detekt.sarif
      - name: Run codeql analysis
        uses: github/codeql-action/analyze@v2
  container:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Custom image tag
        run: |
          echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | cut -d '/' -f2 )" >> $GITHUB_ENV
      - name: Build Image
        run: |
          docker build -t $IMAGE_REPOSITORY:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE_REPOSITORY }}:${{ github.sha }}"
          exit-code: "1"
          hide-progress: false
          format: "sarif"
          output: 'trivy-results.sarif'
          severity: "CRITICAL,HIGH"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
