name: "Build, Test, Scan"

on:   
  push:
  workflow_dispatch:
jobs:
  jar:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and test with Maven
        run: mvn clean --batch-mode package
      - name: Set up codeql
        uses: github/codeql-action/init@v2
        with:
          languages: kotlin
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Run codeql analysis
        uses: github/codeql-action/analyze@v2

  sast:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup detekt
        uses: peter-murray/setup-detekt@v2
        with:
          detekt_version: 1.23
      - name: Run detekt
        run: detekt-cli --base-path . -r sarif:reports/detekt.sarif
        continue-on-error: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: reports/detekt.sarif

  container:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: docker build -t '${{ github.repository }}:${{ github.sha }}' .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ github.repository }}:${{ github.sha }}'
          exit-code: "1"
          hide-progress: false
          format: "sarif"
          output: 'trivy-results-EXAMPLE.sarif'
          severity: "CRITICAL,HIGH"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results-EXAMPLE.sarif'